// ============================================================================
// Handoff Engine — AI Onboarding Document Generator
// ============================================================================
// Generates AI_START_HERE.md, PROJECT_CONTEXT.md, and HANDOFF.md from
// the current memory state. Uses Handlebars templates for formatting.
// ============================================================================

import Handlebars from 'handlebars';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  ProjectMemory,
  HandoffData,
  LanguageInfo,
  FrameworkInfo,
  CommitInfo,
} from '../../types/index.js';
import { getMemoryFilePaths } from '../memory/schema.js';
import { writeText, readText, fileExists } from '../../utils/fs.js';
import { compareMemory } from '../graph/diff.js';
import { promises as fs } from 'node:fs';
import { computeProgress, detectScopeDrift } from '../focus/index.js';
import logger from '../../utils/logger.js';

// ---------------------------------------------------------------------------
// Handlebars Helpers
// ---------------------------------------------------------------------------

Handlebars.registerHelper('date', (isoString: string) => {
  if (!isoString) return 'N/A';
  return new Date(isoString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
});

Handlebars.registerHelper('datetime', (isoString: string) => {
  if (!isoString) return 'N/A';
  return new Date(isoString).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
});

Handlebars.registerHelper('pct', (value: number) => {
  return `${value}%`;
});

Handlebars.registerHelper('confidenceEmoji', (score: number) => {
  if (score >= 80) return '🟢';
  if (score >= 50) return '🟡';
  return '🔴';
});

Handlebars.registerHelper('eq', (a: unknown, b: unknown) => a === b);
Handlebars.registerHelper('gt', (a: number, b: number) => a > b);
Handlebars.registerHelper('ifCond', function (this: unknown, v1: unknown, v2: unknown, options: Handlebars.HelperOptions) {
  if (v1 === v2) return options.fn(this);
  return options.inverse(this);
});

// ---------------------------------------------------------------------------
// Templates (embedded to avoid filesystem issues during npm install)
// ---------------------------------------------------------------------------

const AI_START_HERE_TEMPLATE = `# 🧠 AI_START_HERE — {{projectName}}

> **Auto-generated by [Project-Mind](https://github.com/project-mind/project-mind) v{{version}}**
> Last updated: {{datetime updatedAt}}

---

## 📋 Project Overview

{{#if description}}
{{description}}
{{else}}
*No project description available. Consider adding a README.md.*
{{/if}}

| Attribute | Value |
|-----------|-------|
| **Project** | {{projectName}} |
| **Scenario** | {{scenario}} |
{{#if languages.length}}| **Languages** | {{#each languages}}{{name}} ({{percentage}}%){{#unless @last}}, {{/unless}}{{/each}} |{{/if}}
{{#if frameworks.length}}| **Frameworks** | {{#each frameworks}}{{name}} \`v{{version}}\`{{#unless @last}}, {{/unless}}{{/each}} |{{/if}}
| **Confidence** | {{confidenceEmoji confidence.overall}} {{pct confidence.overall}} |

---

## 🎯 Current Focus

{{#if focusHistory.active}}
**Task:** {{focusHistory.active.task}}
**Status:** {{focusHistory.active.status}}
**Progress:** {{focusProgress.completed}}/{{focusProgress.total}} ({{focusProgress.percentage}}%)

{{#if focusHistory.active.subTasks.length}}
### Subtasks
{{#each focusHistory.active.subTasks}}
- [{{#if (eq status "done")}}x{{else}} {{/if}}] {{description}}
{{/each}}
{{/if}}

{{#if focusHistory.active.blockers.length}}
### Blockers
{{#each focusHistory.active.blockers}}
- {{this}}
{{/each}}
{{/if}}

{{#if scopeDrift.hasDrift}}
> [!WARNING]
> **Scope Drift Detected**
> Expected: {{#each focusHistory.active.expectedModules}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
> Actually Touched:
{{#each scopeDrift.extraModules}}
> - {{this}}
{{/each}}
{{/if}}

{{#if focusHistory.active.linkedCommits.length}}
### Linked Commits
{{#each focusHistory.active.linkedCommits}}
- \`{{this}}\`
{{/each}}
{{/if}}
{{else}}
*No active task. Use \`project-mind start-feature\` to set current focus.*
{{/if}}

---

## 🏗️ Architecture

{{#if architecture.pattern}}
**Pattern:** {{architecture.pattern}}

{{#if architecture.layers.length}}
### Layers

| Layer | Type | Directories |
|-------|------|-------------|
{{#each architecture.layers}}
| {{name}} | \`{{type}}\` | {{#each directories}}{{this}}{{#unless @last}}, {{/unless}}{{/each}} |
{{/each}}
{{/if}}

{{#if architecture.components.length}}
### Components

| Component | Type | Directory | Confidence |
|-----------|------|-----------|------------|
{{#each architecture.components}}
| {{name}} | \`{{type}}\` | {{directory}} | {{confidenceEmoji confidence}} {{pct confidence}} |
{{/each}}
{{/if}}
{{else}}
*Architecture not yet detected. Run \`project-mind init --deep-scan\` for analysis.*
{{/if}}

{{#if inventory.length}}
### 🧩 Component Inventory

{{#each inventory}}
**{{layer}}**
{{#each files}}
- \`{{this}}\`
{{/each}}

{{/each}}
{{/if}}

**Architecture Confidence:** {{confidenceEmoji confidence.architecture}} {{pct confidence.architecture}}

---

---

## 🌟 Key Features

{{#if features.length}}
{{#each features}}
- **{{name}}**: {{files.length}} files across {{components.length}} components.
{{/each}}
{{else}}
*No features extracted yet.*
{{/if}}

---

## 📦 Key Dependencies

{{#if dependencies.length}}
| Dependency | Version | Type | Source |
|------------|---------|------|--------|
{{#each dependencies}}
| **{{name}}** | \`{{version}}\` | {{type}} | {{source}} |
{{/each}}
{{else}}
*No dependencies extracted yet.*
{{/if}}

---
{{#if workflows.length}}
## 🔄 Workflows

{{#each workflows}}
- **{{name}}** (\`{{type}}\`): {{description}}
{{/each}}

*See \`WORKFLOWS.md\` for detailed component paths.*

---

{{/if}}
{{#if timeline.length}}
## 📅 Recent Milestones

{{#each timeline}}
- **{{date date}}**: {{title}} — {{type}}
{{/each}}

{{/if}}

{{#if delta.hasChanges}}
## 🔄 Recent Structural Changes (Delta)

> [!NOTE]
> The following structural changes occurred since the last memory state.

\`\`\`diff
{{#each delta.components.added}}
+ [COMPONENT ADDED] {{name}}
{{/each}}
{{#each delta.components.removed}}
- [COMPONENT REMOVED] {{name}}
{{/each}}
{{#each delta.components.modified}}
  [COMPONENT MODIFIED] {{name}}
{{/each}}
{{#each delta.features.completed}}
+ [FEATURE COMPLETED] {{name}}
{{/each}}
{{#each delta.decisions.added}}
+ [DECISION ADDED] {{title}}
{{/each}}
\`\`\`

---
{{/if}}

{{#if recentCommits.length}}
## 📝 Recent Changes

| Date | Author | Message |
|------|--------|---------|
{{#each recentCommits}}
| {{date date}} | {{author}} | {{message}} |
{{/each}}

{{/if}}
{{#if decisions.length}}
## 🎯 Key Decisions

{{#each decisions}}
### {{title}}

{{description}}

{{#if rejected.length}}
**Rejected:** {{#each rejected}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
{{/if}}
{{#if reason}}
**Reason:** {{reason}}
{{/if}}

---

{{/each}}
{{/if}}
{{#if currentTask}}
## 🔧 Current Task

**{{currentTask.title}}** — {{currentTask.status}}

{{currentTask.description}}

{{#if currentTask.relatedFiles.length}}
**Related files:**
{{#each currentTask.relatedFiles}}
- \`{{this}}\`
{{/each}}
{{/if}}

---

{{/if}}
{{#if keyFiles.length}}
## 📁 Key Files

{{#each keyFiles}}
- \`{{this}}\`
{{/each}}

---

{{/if}}
## 📊 Confidence Scores

| Dimension | Score |
|-----------|-------|
| **Overall** | {{confidenceEmoji confidence.overall}} {{pct confidence.overall}} |
| **Architecture** | {{confidenceEmoji confidence.architecture}} {{pct confidence.architecture}} |
| **Evidence** | {{confidenceEmoji confidence.evidence}} {{pct confidence.evidence}} |
| **Decisions** | {{confidenceEmoji confidence.decisions}} {{pct confidence.decisions}} |
| **Evidence Sources** | {{confidence.evidenceSources}} / {{confidence.maxEvidenceSources}} |

{{#if recentSessions.length}}

---

## 🕐 Recent Sessions

| # | Date | Type | Summary |
|---|------|------|---------|
{{#each recentSessions}}
| {{id}} | {{datetime timestamp}} | {{type}} | {{summary}} |
{{/each}}
{{/if}}

---

*This file is auto-generated. Do not edit manually.*
*Run \`project-mind update\` or \`project-mind handoff\` to regenerate.*
`;

const PROJECT_CONTEXT_TEMPLATE = `# Project Context — {{projectName}}

> Generated by Project-Mind v{{version}} on {{datetime updatedAt}}

## Project Identity

- **Name:** {{projectName}}
- **Scenario:** {{scenario}}
{{#if description}}
- **Description:** {{description}}
{{/if}}

## Technology Stack

{{#if languages.length}}
### Languages
{{#each languages}}
- **{{name}}**: {{fileCount}} files, ~{{lineCount}} lines ({{percentage}}%)
{{/each}}
{{/if}}

{{#if frameworks.length}}
### Frameworks & Libraries
{{#each frameworks}}
- **{{name}}** v{{version}} ({{category}}, confidence: {{pct confidence}})
{{/each}}
{{/if}}

## File Organization

- **Total source files:** {{sourceFiles}}
- **Total lines of code:** {{totalLines}}
{{#if entryPoints.length}}
- **Entry points:** {{#each entryPoints}}\`{{this}}\`{{#unless @last}}, {{/unless}}{{/each}}
{{/if}}

## Evidence Sources

- **Git:** {{#if hasGit}}Available ({{gitCommits}} commits, {{gitAuthors}} authors){{else}}Not available{{/if}}
- **Build files:** {{buildSystems}}
- **Documentation:** {{#if hasReadme}}README present{{else}}No README{{/if}}
- **License:** {{license}}

---

*Auto-generated by Project-Mind. Run \`project-mind update\` to refresh.*
`;

const HANDOFF_TEMPLATE = `# Agent Handoff — {{projectName}}

> This document helps AI coding assistants quickly understand this project.
> Generated by Project-Mind v{{version}} on {{datetime updatedAt}}

## Quick Start

1. Read this file for project context
2. Check \`AI_START_HERE.md\` for architecture and recent changes
3. Check \`DECISIONS.md\` for important technical decisions
4. Check \`MEMORY.json\` for raw structured data

## What This Project Does

{{#if description}}
{{description}}
{{else}}
*No description available. Check the README for details.*
{{/if}}

## Important Constraints

{{#if decisions.length}}
{{#each decisions}}
- **{{title}}**: {{reason}}
{{/each}}
{{else}}
*No constraints recorded yet.*
{{/if}}

## Files You Should Know About

{{#if keyFiles.length}}
{{#each keyFiles}}
- \`{{this}}\`
{{/each}}
{{else}}
*Run \`project-mind init --deep-scan\` to identify key files.*
{{/if}}

{{#if currentTask}}
## Currently Working On

**{{currentTask.title}}** — {{currentTask.status}}

{{currentTask.description}}
{{/if}}

---

*Auto-generated by Project-Mind.*
`;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates all handoff documents from the current memory state.
 */
export async function generateHandoff(
  projectPath: string,
  memory: ProjectMemory,
): Promise<void> {
  const paths = getMemoryFilePaths(projectPath);
  let memoryPrev: ProjectMemory | null = null;

  if (await fileExists(paths.memoryPrev)) {
    try {
      const prevStr = await fs.readFile(paths.memoryPrev, 'utf-8');
      memoryPrev = JSON.parse(prevStr) as ProjectMemory;
    } catch (err) {
      // Ignore
    }
  }

  const delta = compareMemory(memoryPrev, memory);
  const data = buildHandoffData(memory, delta);

  // Compile templates
  const aiStartHere = Handlebars.compile(AI_START_HERE_TEMPLATE)(data);
  const projectContext = Handlebars.compile(PROJECT_CONTEXT_TEMPLATE)(data);
  const handoff = Handlebars.compile(HANDOFF_TEMPLATE)(data);

  // Write all handoff files
  await Promise.all([
    writeText(paths.aiStartHere, aiStartHere),
    writeText(paths.projectContext, projectContext),
    writeText(paths.handoff, handoff),
  ]);

  logger.success(`Generated AI_START_HERE.md`);
  logger.success(`Generated PROJECT_CONTEXT.md`);
  logger.success(`Generated HANDOFF.md`);
}

// ---------------------------------------------------------------------------
// Internal
// ---------------------------------------------------------------------------

function buildHandoffData(memory: ProjectMemory, delta: any): Record<string, unknown> {
  const recentSessions = memory.sessions
    .slice(-5)
    .reverse();

  const recentCommits = memory.evidence.git?.recentCommits?.slice(0, 10) || [];

  // Identify key files from entry points + hotspots
  const keyFiles = new Set<string>();
  for (const ep of memory.evidence.sourceCode.entryPoints) {
    keyFiles.add(ep);
  }
  if (memory.evidence.git?.hotspots) {
    for (const hs of memory.evidence.git.hotspots.slice(0, 5)) {
      keyFiles.add(hs.filePath);
    }
  }

  let focusProgress = { completed: 0, total: 0, percentage: 0 };
  let scopeDrift = { hasDrift: false, extraModules: [] as string[] };
  
  if (memory.focusHistory.active) {
    focusProgress = computeProgress(memory);
    scopeDrift = detectScopeDrift(memory);
  }

  return {
    projectName: memory.projectName,
    version: memory.version,
    description: memory.description,
    scenario: formatScenario(memory.scenario),
    createdAt: memory.createdAt,
    updatedAt: memory.updatedAt,
    languages: memory.evidence.sourceCode.languages,
    frameworks: memory.evidence.buildFiles.frameworks,
    architecture: memory.architecture,
    workflows: memory.workflows?.slice(0, 5) || [],
    features: memory.features?.slice(0, 10) || [],
    dependencies: buildDependenciesList(memory.evidence.buildFiles.dependencies),
    inventory: buildInventoryList(memory.architecture.components),
    timeline: memory.timeline?.slice(-5).reverse() || [],
    recentCommits,
    recentSessions,
    decisions: memory.decisions,
    focusHistory: memory.focusHistory,
    focusProgress,
    scopeDrift,
    confidence: memory.confidence,
    keyFiles: Array.from(keyFiles),
    sourceFiles: memory.evidence.sourceCode.totalFiles,
    totalLines: memory.evidence.sourceCode.totalLines.toLocaleString(),
    entryPoints: memory.evidence.sourceCode.entryPoints,
    hasGit: memory.evidence.git?.isGitRepo ?? false,
    gitCommits: memory.evidence.git?.totalCommits ?? 0,
    gitAuthors: memory.evidence.git?.authors.length ?? 0,
    buildSystems: memory.evidence.buildFiles.buildSystems.map(b => b.name).join(', ') || 'none',
    hasReadme: memory.evidence.documentation.hasReadme,
    license: memory.evidence.documentation.licenseType || 'not detected',
    delta,
  };
}

function formatScenario(scenario: string): string {
  switch (scenario) {
    case 'brand-new': return 'Brand New Project';
    case 'existing': return 'Existing Project (no Git)';
    case 'mature': return 'Mature Project (with Git)';
    case 'fully-tracked': return 'Fully Tracked Project';
    default: return scenario;
  }
}

function buildDependenciesList(deps: any[]): any[] {
  if (!deps) return [];
  // Filter out some internal noise if needed, but for now just return top 30
  // Sort by name for stability
  return [...deps]
    .filter(d => d.type === 'production')
    .sort((a, b) => a.name.localeCompare(b.name))
    .slice(0, 30);
}

function buildInventoryList(components: any[]): any[] {
  if (!components) return [];
  const inventoryMap = new Map<string, string[]>();

  for (const comp of components) {
    if (comp.files && comp.files.length > 0) {
      const layer = comp.type.charAt(0).toUpperCase() + comp.type.slice(1) + 's';
      const existing = inventoryMap.get(layer) || [];
      
      let item = comp.files[0];
      if (comp.endpoints && comp.endpoints.length > 0) {
        item += ` ⚡ [${comp.endpoints.join(', ')}]`;
      }
      
      inventoryMap.set(layer, [...existing, item]);
    }
  }

  const inventory = [];
  for (const [layer, files] of inventoryMap.entries()) {
    inventory.push({
      layer,
      files: files.slice(0, 15) // cap at 15 files per type to save tokens
    });
  }
  
  return inventory.sort((a, b) => a.layer.localeCompare(b.layer));
}
