// ============================================================================
// CLI Command: install-hooks
// ============================================================================
// Installs a Git post-commit hook that automatically runs
// `project-mind update --quiet` after every commit.
// ============================================================================

import { Command } from 'commander';
import path from 'node:path';
import { promises as fs } from 'node:fs';
import logger from '../utils/logger.js';
import { getProjectRoot, fileExists, ensureDir, readText } from '../utils/fs.js';
import { isInitialized } from '../engines/memory/index.js';
import { isGitRepo } from '../utils/git.js';

const HOOK_MARKER = '# project-mind-hook';

const HOOK_SCRIPT_UNIX = `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by project-mind install-hooks
# Runs project-mind update after every commit

# Check if project-mind is available
if command -v project-mind >/dev/null 2>&1; then
  project-mind update --quiet
elif command -v npx >/dev/null 2>&1; then
  npx project-mind update --quiet
fi
`;

const HOOK_SCRIPT_WINDOWS = `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by project-mind install-hooks
# Runs project-mind update after every commit (Windows-compatible)

# Check if project-mind is available
if command -v project-mind >/dev/null 2>&1; then
  project-mind update --quiet
elif command -v npx >/dev/null 2>&1; then
  npx project-mind update --quiet
fi
`;

export const installHooksCommand = new Command('install-hooks')
  .description('Install Git hooks for automatic memory updates')
  .option('-p, --project-dir <path>', 'Project directory (defaults to current)')
  .option('--uninstall', 'Remove the installed Git hooks')
  .action(async (options) => {
    try {
      const projectPath = options.projectDir
        ? options.projectDir
        : await getProjectRoot();

      // Verify prerequisites
      if (!(await isGitRepo(projectPath))) {
        logger.error('This is not a Git repository. Git hooks require a .git/ directory.');
        logger.info('Run `git init` first, then try again.');
        process.exit(1);
      }

      if (!(await isInitialized(projectPath))) {
        logger.error('Project-Mind is not initialized. Run `project-mind init` first.');
        process.exit(1);
      }

      const hooksDir = path.join(projectPath, '.git', 'hooks');
      const hookFile = path.join(hooksDir, 'post-commit');

      if (options.uninstall) {
        await uninstallHook(hookFile);
        return;
      }

      await installHook(hooksDir, hookFile);
    } catch (err) {
      logger.error(`Hook installation failed: ${err instanceof Error ? err.message : String(err)}`);
      process.exit(1);
    }
  });

export async function installHook(hooksDir: string, hookFile: string, quiet = false): Promise<void> {
  await ensureDir(hooksDir);

  // Check for existing hook
  if (await fileExists(hookFile)) {
    const existingContent = await readText(hookFile);
    if (existingContent && existingContent.includes(HOOK_MARKER)) {
      logger.warn('Project-Mind Git hook is already installed.');
      logger.info('Use --uninstall to remove it first if you want to reinstall.');
      return;
    }

    // Existing hook from another tool — append
    logger.warn('Existing post-commit hook detected. Appending project-mind hook.');
    const appendScript = `\n\n${HOOK_MARKER}\n# Appended by project-mind\nif command -v project-mind >/dev/null 2>&1; then\n  project-mind update --quiet\nfi\n`;
    await fs.appendFile(hookFile, appendScript, 'utf-8');
  } else {
    // Create new hook
    const isWindows = process.platform === 'win32';
    const script = isWindows ? HOOK_SCRIPT_WINDOWS : HOOK_SCRIPT_UNIX;
    await fs.writeFile(hookFile, script, { mode: 0o755, encoding: 'utf-8' });
  }

  // Ensure executable (Unix)
  try {
    await fs.chmod(hookFile, 0o755);
  } catch {
    // chmod may fail on Windows, that's fine
  }

  if (!quiet) {
    logger.success('Git post-commit hook installed successfully!');
    logger.blank();
    logger.info('What happens now:');
    logger.bullet('After every `git commit`, project-mind will automatically update memory');
    logger.bullet('AI_START_HERE.md will be regenerated with latest changes');
    logger.bullet('Session records will track each update');
    logger.blank();
    logger.info('To uninstall: `project-mind install-hooks --uninstall`');
  }
}

async function uninstallHook(hookFile: string): Promise<void> {
  if (!(await fileExists(hookFile))) {
    logger.info('No post-commit hook found. Nothing to uninstall.');
    return;
  }

  const content = await readText(hookFile);
  if (!content || !content.includes(HOOK_MARKER)) {
    logger.info('No project-mind hook found in post-commit. Nothing to uninstall.');
    return;
  }

  // If the entire hook is ours, remove the file
  const lines = content.split('\n');
  const nonProjectMindLines = lines.filter(line =>
    !line.includes('project-mind') &&
    !line.includes(HOOK_MARKER) &&
    line.trim() !== '#!/bin/sh' &&
    line.trim() !== ''
  );

  if (nonProjectMindLines.length === 0) {
    // Entire hook is ours — remove the file
    await fs.unlink(hookFile);
    logger.success('Git post-commit hook removed.');
  } else {
    // Other hooks exist — remove only our section
    const filteredContent = content
      .replace(/\n*# project-mind-hook[\s\S]*?(?=\n#[^!]|\n*$)/g, '')
      .trim() + '\n';
    await fs.writeFile(hookFile, filteredContent, { mode: 0o755, encoding: 'utf-8' });
    logger.success('Project-mind hook removed. Other hooks preserved.');
  }
}
