// ============================================================================
// CLI Command: install-hooks
// ============================================================================
// Installs Git post-commit and post-checkout hooks that automatically run
// `project-mind update --quiet` after every change.
// ============================================================================

import { Command } from 'commander';
import path from 'node:path';
import { promises as fs } from 'node:fs';
import logger from '../utils/logger.js';
import { getProjectRoot, fileExists, ensureDir, readText, isDirectory } from '../utils/fs.js';
import { isInitialized } from '../engines/memory/index.js';
import { isGitRepo } from '../utils/git.js';

const HOOK_MARKER_START = '# --- PROJECT-MIND HOOK START ---';
const HOOK_MARKER_END = '# --- PROJECT-MIND HOOK END ---';

const HOOK_SCRIPT_BODY = `(
  if command -v project-mind >/dev/null 2>&1; then
    project-mind update --quiet >> .project-mind/derived/update.log 2>&1
  elif command -v npx >/dev/null 2>&1; then
    npx project-mind update --quiet >> .project-mind/derived/update.log 2>&1
  fi
) &`;

const HOOK_SCRIPT_FULL = `#!/bin/sh
${HOOK_MARKER_START}
# Auto-generated by project-mind install-hooks
# Runs project-mind update in the background after commits and checkouts
${HOOK_SCRIPT_BODY}
${HOOK_MARKER_END}
`;

const HOOK_APPEND_BLOCK = `\n\n${HOOK_MARKER_START}\n# Appended by project-mind\n${HOOK_SCRIPT_BODY}\n${HOOK_MARKER_END}\n`;

export const installHooksCommand = new Command('install-hooks')
  .description('Install Git hooks for automatic memory updates')
  .option('-p, --project-dir <path>', 'Project directory (defaults to current)')
  .option('--uninstall', 'Remove the installed Git hooks')
  .action(async (options) => {
    try {
      const projectPath = options.projectDir
        ? options.projectDir
        : await getProjectRoot();

      // Verify prerequisites
      if (!(await isGitRepo(projectPath))) {
        logger.error('This is not a Git repository. Git hooks require a .git/ directory.');
        logger.info('Run `git init` first, then try again.');
        process.exit(1);
      }

      if (!(await isInitialized(projectPath))) {
        logger.error('Project-Mind is not initialized. Run `project-mind init` first.');
        process.exit(1);
      }

      let hooksDir = path.join(projectPath, '.git', 'hooks');
      const huskyDir = path.join(projectPath, '.husky');

      // Detect Husky
      let usingHusky = false;
      if (await isDirectory(huskyDir)) {
        usingHusky = true;
        hooksDir = huskyDir;
        logger.info('Detected Husky. Installing hooks into .husky/ directory.');
      }

      const postCommitFile = path.join(hooksDir, 'post-commit');
      const postCheckoutFile = path.join(hooksDir, 'post-checkout');

      if (options.uninstall) {
        let uninstalledCommit = await uninstallHook(postCommitFile);
        let uninstalledCheckout = await uninstallHook(postCheckoutFile);
        
        if (!uninstalledCommit && !uninstalledCheckout) {
          logger.info('No Project-Mind hooks found. Nothing to uninstall.');
        } else {
          logger.success('Git hooks uninstalled successfully.');
        }
        return;
      }

      await installHook(hooksDir, postCommitFile, 'post-commit', true);
      await installHook(hooksDir, postCheckoutFile, 'post-checkout', false);
      
      logger.success('Git hooks installed successfully!');
      logger.blank();
      logger.info('What happens now:');
      logger.bullet('After every `git commit` and `git checkout`, project-mind will automatically update memory');
      logger.bullet('Updates run quietly in the background without blocking your terminal');
      logger.bullet('Logs are available at `.project-mind/derived/update.log`');
      logger.blank();
      logger.info('To uninstall: `project-mind install-hooks --uninstall`');

    } catch (err) {
      logger.error(`Hook installation failed: ${err instanceof Error ? err.message : String(err)}`);
      process.exit(1);
    }
  });

export async function installHook(hooksDir: string, hookFile: string, hookName: string, showLogs = false): Promise<void> {
  await ensureDir(hooksDir);

  // Check for existing hook
  if (await fileExists(hookFile)) {
    const existingContent = await readText(hookFile);
    if (existingContent && existingContent.includes(HOOK_MARKER_START)) {
      if (showLogs) logger.warn(`Project-Mind ${hookName} hook is already installed.`);
      return;
    }

    // Existing hook from another tool — append
    if (showLogs) logger.warn(`Existing ${hookName} hook detected. Appending project-mind hook.`);
    await fs.appendFile(hookFile, HOOK_APPEND_BLOCK, 'utf-8');
  } else {
    // Create new hook
    await fs.writeFile(hookFile, HOOK_SCRIPT_FULL, { mode: 0o755, encoding: 'utf-8' });
  }

  // Ensure executable (Unix)
  try {
    await fs.chmod(hookFile, 0o755);
  } catch {
    // chmod may fail on Windows, that's fine
  }
}

async function uninstallHook(hookFile: string): Promise<boolean> {
  if (!(await fileExists(hookFile))) {
    return false;
  }

  const content = await readText(hookFile);
  if (!content || !content.includes(HOOK_MARKER_START)) {
    return false;
  }

  // Remove block using string manipulation
  const startIndex = content.indexOf(HOOK_MARKER_START);
  const endIndex = content.indexOf(HOOK_MARKER_END, startIndex);

  if (startIndex !== -1 && endIndex !== -1) {
    const prefix = content.slice(0, startIndex);
    const suffix = content.slice(endIndex + HOOK_MARKER_END.length);
    const newContent = (prefix + suffix).trim();

    if (newContent === '' || newContent === '#!/bin/sh') {
      // The file only contained our script
      await fs.unlink(hookFile);
    } else {
      // Other things existed, preserve them
      await fs.writeFile(hookFile, newContent + '\n', { mode: 0o755, encoding: 'utf-8' });
    }
    return true;
  }

  return false;
}
